// Both the arm and arm64 arches define this enum.
//
// To work around this we define it on its own so that it overrides the values
// imported from the modules we generate below.
pub type perf_event_arm_regs = ::std::os::raw::c_uint;
mod arm64 {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_ARM64_X0: perf_event_arm_regs = 0;
    pub const PERF_REG_ARM64_X1: perf_event_arm_regs = 1;
    pub const PERF_REG_ARM64_X2: perf_event_arm_regs = 2;
    pub const PERF_REG_ARM64_X3: perf_event_arm_regs = 3;
    pub const PERF_REG_ARM64_X4: perf_event_arm_regs = 4;
    pub const PERF_REG_ARM64_X5: perf_event_arm_regs = 5;
    pub const PERF_REG_ARM64_X6: perf_event_arm_regs = 6;
    pub const PERF_REG_ARM64_X7: perf_event_arm_regs = 7;
    pub const PERF_REG_ARM64_X8: perf_event_arm_regs = 8;
    pub const PERF_REG_ARM64_X9: perf_event_arm_regs = 9;
    pub const PERF_REG_ARM64_X10: perf_event_arm_regs = 10;
    pub const PERF_REG_ARM64_X11: perf_event_arm_regs = 11;
    pub const PERF_REG_ARM64_X12: perf_event_arm_regs = 12;
    pub const PERF_REG_ARM64_X13: perf_event_arm_regs = 13;
    pub const PERF_REG_ARM64_X14: perf_event_arm_regs = 14;
    pub const PERF_REG_ARM64_X15: perf_event_arm_regs = 15;
    pub const PERF_REG_ARM64_X16: perf_event_arm_regs = 16;
    pub const PERF_REG_ARM64_X17: perf_event_arm_regs = 17;
    pub const PERF_REG_ARM64_X18: perf_event_arm_regs = 18;
    pub const PERF_REG_ARM64_X19: perf_event_arm_regs = 19;
    pub const PERF_REG_ARM64_X20: perf_event_arm_regs = 20;
    pub const PERF_REG_ARM64_X21: perf_event_arm_regs = 21;
    pub const PERF_REG_ARM64_X22: perf_event_arm_regs = 22;
    pub const PERF_REG_ARM64_X23: perf_event_arm_regs = 23;
    pub const PERF_REG_ARM64_X24: perf_event_arm_regs = 24;
    pub const PERF_REG_ARM64_X25: perf_event_arm_regs = 25;
    pub const PERF_REG_ARM64_X26: perf_event_arm_regs = 26;
    pub const PERF_REG_ARM64_X27: perf_event_arm_regs = 27;
    pub const PERF_REG_ARM64_X28: perf_event_arm_regs = 28;
    pub const PERF_REG_ARM64_X29: perf_event_arm_regs = 29;
    pub const PERF_REG_ARM64_LR: perf_event_arm_regs = 30;
    pub const PERF_REG_ARM64_SP: perf_event_arm_regs = 31;
    pub const PERF_REG_ARM64_PC: perf_event_arm_regs = 32;
    pub const PERF_REG_ARM64_MAX: perf_event_arm_regs = 33;
    pub type perf_event_arm_regs = ::std::os::raw::c_uint;
}
pub use arm64::*;
mod arm {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_ARM_R0: perf_event_arm_regs = 0;
    pub const PERF_REG_ARM_R1: perf_event_arm_regs = 1;
    pub const PERF_REG_ARM_R2: perf_event_arm_regs = 2;
    pub const PERF_REG_ARM_R3: perf_event_arm_regs = 3;
    pub const PERF_REG_ARM_R4: perf_event_arm_regs = 4;
    pub const PERF_REG_ARM_R5: perf_event_arm_regs = 5;
    pub const PERF_REG_ARM_R6: perf_event_arm_regs = 6;
    pub const PERF_REG_ARM_R7: perf_event_arm_regs = 7;
    pub const PERF_REG_ARM_R8: perf_event_arm_regs = 8;
    pub const PERF_REG_ARM_R9: perf_event_arm_regs = 9;
    pub const PERF_REG_ARM_R10: perf_event_arm_regs = 10;
    pub const PERF_REG_ARM_FP: perf_event_arm_regs = 11;
    pub const PERF_REG_ARM_IP: perf_event_arm_regs = 12;
    pub const PERF_REG_ARM_SP: perf_event_arm_regs = 13;
    pub const PERF_REG_ARM_LR: perf_event_arm_regs = 14;
    pub const PERF_REG_ARM_PC: perf_event_arm_regs = 15;
    pub const PERF_REG_ARM_MAX: perf_event_arm_regs = 16;
    pub type perf_event_arm_regs = ::std::os::raw::c_uint;
}
pub use arm::*;
mod csky {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_CSKY_TLS: perf_event_csky_regs = 0;
    pub const PERF_REG_CSKY_LR: perf_event_csky_regs = 1;
    pub const PERF_REG_CSKY_PC: perf_event_csky_regs = 2;
    pub const PERF_REG_CSKY_SR: perf_event_csky_regs = 3;
    pub const PERF_REG_CSKY_SP: perf_event_csky_regs = 4;
    pub const PERF_REG_CSKY_ORIG_A0: perf_event_csky_regs = 5;
    pub const PERF_REG_CSKY_A0: perf_event_csky_regs = 6;
    pub const PERF_REG_CSKY_A1: perf_event_csky_regs = 7;
    pub const PERF_REG_CSKY_A2: perf_event_csky_regs = 8;
    pub const PERF_REG_CSKY_A3: perf_event_csky_regs = 9;
    pub const PERF_REG_CSKY_REGS0: perf_event_csky_regs = 10;
    pub const PERF_REG_CSKY_REGS1: perf_event_csky_regs = 11;
    pub const PERF_REG_CSKY_REGS2: perf_event_csky_regs = 12;
    pub const PERF_REG_CSKY_REGS3: perf_event_csky_regs = 13;
    pub const PERF_REG_CSKY_REGS4: perf_event_csky_regs = 14;
    pub const PERF_REG_CSKY_REGS5: perf_event_csky_regs = 15;
    pub const PERF_REG_CSKY_REGS6: perf_event_csky_regs = 16;
    pub const PERF_REG_CSKY_REGS7: perf_event_csky_regs = 17;
    pub const PERF_REG_CSKY_REGS8: perf_event_csky_regs = 18;
    pub const PERF_REG_CSKY_REGS9: perf_event_csky_regs = 19;
    pub const PERF_REG_CSKY_MAX: perf_event_csky_regs = 20;
    pub type perf_event_csky_regs = ::std::os::raw::c_uint;
}
pub use csky::*;
mod mips {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_MIPS_PC: perf_event_mips_regs = 0;
    pub const PERF_REG_MIPS_R1: perf_event_mips_regs = 1;
    pub const PERF_REG_MIPS_R2: perf_event_mips_regs = 2;
    pub const PERF_REG_MIPS_R3: perf_event_mips_regs = 3;
    pub const PERF_REG_MIPS_R4: perf_event_mips_regs = 4;
    pub const PERF_REG_MIPS_R5: perf_event_mips_regs = 5;
    pub const PERF_REG_MIPS_R6: perf_event_mips_regs = 6;
    pub const PERF_REG_MIPS_R7: perf_event_mips_regs = 7;
    pub const PERF_REG_MIPS_R8: perf_event_mips_regs = 8;
    pub const PERF_REG_MIPS_R9: perf_event_mips_regs = 9;
    pub const PERF_REG_MIPS_R10: perf_event_mips_regs = 10;
    pub const PERF_REG_MIPS_R11: perf_event_mips_regs = 11;
    pub const PERF_REG_MIPS_R12: perf_event_mips_regs = 12;
    pub const PERF_REG_MIPS_R13: perf_event_mips_regs = 13;
    pub const PERF_REG_MIPS_R14: perf_event_mips_regs = 14;
    pub const PERF_REG_MIPS_R15: perf_event_mips_regs = 15;
    pub const PERF_REG_MIPS_R16: perf_event_mips_regs = 16;
    pub const PERF_REG_MIPS_R17: perf_event_mips_regs = 17;
    pub const PERF_REG_MIPS_R18: perf_event_mips_regs = 18;
    pub const PERF_REG_MIPS_R19: perf_event_mips_regs = 19;
    pub const PERF_REG_MIPS_R20: perf_event_mips_regs = 20;
    pub const PERF_REG_MIPS_R21: perf_event_mips_regs = 21;
    pub const PERF_REG_MIPS_R22: perf_event_mips_regs = 22;
    pub const PERF_REG_MIPS_R23: perf_event_mips_regs = 23;
    pub const PERF_REG_MIPS_R24: perf_event_mips_regs = 24;
    pub const PERF_REG_MIPS_R25: perf_event_mips_regs = 25;
    pub const PERF_REG_MIPS_R26: perf_event_mips_regs = 26;
    pub const PERF_REG_MIPS_R27: perf_event_mips_regs = 27;
    pub const PERF_REG_MIPS_R28: perf_event_mips_regs = 28;
    pub const PERF_REG_MIPS_R29: perf_event_mips_regs = 29;
    pub const PERF_REG_MIPS_R30: perf_event_mips_regs = 30;
    pub const PERF_REG_MIPS_R31: perf_event_mips_regs = 31;
    pub const PERF_REG_MIPS_MAX: perf_event_mips_regs = 32;
    pub type perf_event_mips_regs = ::std::os::raw::c_uint;
}
pub use mips::*;
mod powerpc {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_POWERPC_R0: perf_event_powerpc_regs = 0;
    pub const PERF_REG_POWERPC_R1: perf_event_powerpc_regs = 1;
    pub const PERF_REG_POWERPC_R2: perf_event_powerpc_regs = 2;
    pub const PERF_REG_POWERPC_R3: perf_event_powerpc_regs = 3;
    pub const PERF_REG_POWERPC_R4: perf_event_powerpc_regs = 4;
    pub const PERF_REG_POWERPC_R5: perf_event_powerpc_regs = 5;
    pub const PERF_REG_POWERPC_R6: perf_event_powerpc_regs = 6;
    pub const PERF_REG_POWERPC_R7: perf_event_powerpc_regs = 7;
    pub const PERF_REG_POWERPC_R8: perf_event_powerpc_regs = 8;
    pub const PERF_REG_POWERPC_R9: perf_event_powerpc_regs = 9;
    pub const PERF_REG_POWERPC_R10: perf_event_powerpc_regs = 10;
    pub const PERF_REG_POWERPC_R11: perf_event_powerpc_regs = 11;
    pub const PERF_REG_POWERPC_R12: perf_event_powerpc_regs = 12;
    pub const PERF_REG_POWERPC_R13: perf_event_powerpc_regs = 13;
    pub const PERF_REG_POWERPC_R14: perf_event_powerpc_regs = 14;
    pub const PERF_REG_POWERPC_R15: perf_event_powerpc_regs = 15;
    pub const PERF_REG_POWERPC_R16: perf_event_powerpc_regs = 16;
    pub const PERF_REG_POWERPC_R17: perf_event_powerpc_regs = 17;
    pub const PERF_REG_POWERPC_R18: perf_event_powerpc_regs = 18;
    pub const PERF_REG_POWERPC_R19: perf_event_powerpc_regs = 19;
    pub const PERF_REG_POWERPC_R20: perf_event_powerpc_regs = 20;
    pub const PERF_REG_POWERPC_R21: perf_event_powerpc_regs = 21;
    pub const PERF_REG_POWERPC_R22: perf_event_powerpc_regs = 22;
    pub const PERF_REG_POWERPC_R23: perf_event_powerpc_regs = 23;
    pub const PERF_REG_POWERPC_R24: perf_event_powerpc_regs = 24;
    pub const PERF_REG_POWERPC_R25: perf_event_powerpc_regs = 25;
    pub const PERF_REG_POWERPC_R26: perf_event_powerpc_regs = 26;
    pub const PERF_REG_POWERPC_R27: perf_event_powerpc_regs = 27;
    pub const PERF_REG_POWERPC_R28: perf_event_powerpc_regs = 28;
    pub const PERF_REG_POWERPC_R29: perf_event_powerpc_regs = 29;
    pub const PERF_REG_POWERPC_R30: perf_event_powerpc_regs = 30;
    pub const PERF_REG_POWERPC_R31: perf_event_powerpc_regs = 31;
    pub const PERF_REG_POWERPC_NIP: perf_event_powerpc_regs = 32;
    pub const PERF_REG_POWERPC_MSR: perf_event_powerpc_regs = 33;
    pub const PERF_REG_POWERPC_ORIG_R3: perf_event_powerpc_regs = 34;
    pub const PERF_REG_POWERPC_CTR: perf_event_powerpc_regs = 35;
    pub const PERF_REG_POWERPC_LINK: perf_event_powerpc_regs = 36;
    pub const PERF_REG_POWERPC_XER: perf_event_powerpc_regs = 37;
    pub const PERF_REG_POWERPC_CCR: perf_event_powerpc_regs = 38;
    pub const PERF_REG_POWERPC_SOFTE: perf_event_powerpc_regs = 39;
    pub const PERF_REG_POWERPC_TRAP: perf_event_powerpc_regs = 40;
    pub const PERF_REG_POWERPC_DAR: perf_event_powerpc_regs = 41;
    pub const PERF_REG_POWERPC_DSISR: perf_event_powerpc_regs = 42;
    pub const PERF_REG_POWERPC_SIER: perf_event_powerpc_regs = 43;
    pub const PERF_REG_POWERPC_MMCRA: perf_event_powerpc_regs = 44;
    pub const PERF_REG_POWERPC_MMCR0: perf_event_powerpc_regs = 45;
    pub const PERF_REG_POWERPC_MMCR1: perf_event_powerpc_regs = 46;
    pub const PERF_REG_POWERPC_MMCR2: perf_event_powerpc_regs = 47;
    pub const PERF_REG_POWERPC_MMCR3: perf_event_powerpc_regs = 48;
    pub const PERF_REG_POWERPC_SIER2: perf_event_powerpc_regs = 49;
    pub const PERF_REG_POWERPC_SIER3: perf_event_powerpc_regs = 50;
    pub const PERF_REG_POWERPC_PMC1: perf_event_powerpc_regs = 51;
    pub const PERF_REG_POWERPC_PMC2: perf_event_powerpc_regs = 52;
    pub const PERF_REG_POWERPC_PMC3: perf_event_powerpc_regs = 53;
    pub const PERF_REG_POWERPC_PMC4: perf_event_powerpc_regs = 54;
    pub const PERF_REG_POWERPC_PMC5: perf_event_powerpc_regs = 55;
    pub const PERF_REG_POWERPC_PMC6: perf_event_powerpc_regs = 56;
    pub const PERF_REG_POWERPC_SDAR: perf_event_powerpc_regs = 57;
    pub const PERF_REG_POWERPC_SIAR: perf_event_powerpc_regs = 58;
    pub const PERF_REG_POWERPC_MAX: perf_event_powerpc_regs = 45;
    pub const PERF_REG_EXTENDED_MAX: perf_event_powerpc_regs = 59;
    pub type perf_event_powerpc_regs = ::std::os::raw::c_uint;
}
pub use powerpc::*;
mod riscv {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_RISCV_PC: perf_event_riscv_regs = 0;
    pub const PERF_REG_RISCV_RA: perf_event_riscv_regs = 1;
    pub const PERF_REG_RISCV_SP: perf_event_riscv_regs = 2;
    pub const PERF_REG_RISCV_GP: perf_event_riscv_regs = 3;
    pub const PERF_REG_RISCV_TP: perf_event_riscv_regs = 4;
    pub const PERF_REG_RISCV_T0: perf_event_riscv_regs = 5;
    pub const PERF_REG_RISCV_T1: perf_event_riscv_regs = 6;
    pub const PERF_REG_RISCV_T2: perf_event_riscv_regs = 7;
    pub const PERF_REG_RISCV_S0: perf_event_riscv_regs = 8;
    pub const PERF_REG_RISCV_S1: perf_event_riscv_regs = 9;
    pub const PERF_REG_RISCV_A0: perf_event_riscv_regs = 10;
    pub const PERF_REG_RISCV_A1: perf_event_riscv_regs = 11;
    pub const PERF_REG_RISCV_A2: perf_event_riscv_regs = 12;
    pub const PERF_REG_RISCV_A3: perf_event_riscv_regs = 13;
    pub const PERF_REG_RISCV_A4: perf_event_riscv_regs = 14;
    pub const PERF_REG_RISCV_A5: perf_event_riscv_regs = 15;
    pub const PERF_REG_RISCV_A6: perf_event_riscv_regs = 16;
    pub const PERF_REG_RISCV_A7: perf_event_riscv_regs = 17;
    pub const PERF_REG_RISCV_S2: perf_event_riscv_regs = 18;
    pub const PERF_REG_RISCV_S3: perf_event_riscv_regs = 19;
    pub const PERF_REG_RISCV_S4: perf_event_riscv_regs = 20;
    pub const PERF_REG_RISCV_S5: perf_event_riscv_regs = 21;
    pub const PERF_REG_RISCV_S6: perf_event_riscv_regs = 22;
    pub const PERF_REG_RISCV_S7: perf_event_riscv_regs = 23;
    pub const PERF_REG_RISCV_S8: perf_event_riscv_regs = 24;
    pub const PERF_REG_RISCV_S9: perf_event_riscv_regs = 25;
    pub const PERF_REG_RISCV_S10: perf_event_riscv_regs = 26;
    pub const PERF_REG_RISCV_S11: perf_event_riscv_regs = 27;
    pub const PERF_REG_RISCV_T3: perf_event_riscv_regs = 28;
    pub const PERF_REG_RISCV_T4: perf_event_riscv_regs = 29;
    pub const PERF_REG_RISCV_T5: perf_event_riscv_regs = 30;
    pub const PERF_REG_RISCV_T6: perf_event_riscv_regs = 31;
    pub const PERF_REG_RISCV_MAX: perf_event_riscv_regs = 32;
    pub type perf_event_riscv_regs = ::std::os::raw::c_uint;
}
pub use riscv::*;
mod s390 {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_S390_R0: perf_event_s390_regs = 0;
    pub const PERF_REG_S390_R1: perf_event_s390_regs = 1;
    pub const PERF_REG_S390_R2: perf_event_s390_regs = 2;
    pub const PERF_REG_S390_R3: perf_event_s390_regs = 3;
    pub const PERF_REG_S390_R4: perf_event_s390_regs = 4;
    pub const PERF_REG_S390_R5: perf_event_s390_regs = 5;
    pub const PERF_REG_S390_R6: perf_event_s390_regs = 6;
    pub const PERF_REG_S390_R7: perf_event_s390_regs = 7;
    pub const PERF_REG_S390_R8: perf_event_s390_regs = 8;
    pub const PERF_REG_S390_R9: perf_event_s390_regs = 9;
    pub const PERF_REG_S390_R10: perf_event_s390_regs = 10;
    pub const PERF_REG_S390_R11: perf_event_s390_regs = 11;
    pub const PERF_REG_S390_R12: perf_event_s390_regs = 12;
    pub const PERF_REG_S390_R13: perf_event_s390_regs = 13;
    pub const PERF_REG_S390_R14: perf_event_s390_regs = 14;
    pub const PERF_REG_S390_R15: perf_event_s390_regs = 15;
    pub const PERF_REG_S390_FP0: perf_event_s390_regs = 16;
    pub const PERF_REG_S390_FP1: perf_event_s390_regs = 17;
    pub const PERF_REG_S390_FP2: perf_event_s390_regs = 18;
    pub const PERF_REG_S390_FP3: perf_event_s390_regs = 19;
    pub const PERF_REG_S390_FP4: perf_event_s390_regs = 20;
    pub const PERF_REG_S390_FP5: perf_event_s390_regs = 21;
    pub const PERF_REG_S390_FP6: perf_event_s390_regs = 22;
    pub const PERF_REG_S390_FP7: perf_event_s390_regs = 23;
    pub const PERF_REG_S390_FP8: perf_event_s390_regs = 24;
    pub const PERF_REG_S390_FP9: perf_event_s390_regs = 25;
    pub const PERF_REG_S390_FP10: perf_event_s390_regs = 26;
    pub const PERF_REG_S390_FP11: perf_event_s390_regs = 27;
    pub const PERF_REG_S390_FP12: perf_event_s390_regs = 28;
    pub const PERF_REG_S390_FP13: perf_event_s390_regs = 29;
    pub const PERF_REG_S390_FP14: perf_event_s390_regs = 30;
    pub const PERF_REG_S390_FP15: perf_event_s390_regs = 31;
    pub const PERF_REG_S390_MASK: perf_event_s390_regs = 32;
    pub const PERF_REG_S390_PC: perf_event_s390_regs = 33;
    pub const PERF_REG_S390_MAX: perf_event_s390_regs = 34;
    pub type perf_event_s390_regs = ::std::os::raw::c_uint;
}
pub use s390::*;
mod x86 {
    /* automatically generated by rust-bindgen 0.63.0 */

    pub const PERF_REG_X86_AX: perf_event_x86_regs = 0;
    pub const PERF_REG_X86_BX: perf_event_x86_regs = 1;
    pub const PERF_REG_X86_CX: perf_event_x86_regs = 2;
    pub const PERF_REG_X86_DX: perf_event_x86_regs = 3;
    pub const PERF_REG_X86_SI: perf_event_x86_regs = 4;
    pub const PERF_REG_X86_DI: perf_event_x86_regs = 5;
    pub const PERF_REG_X86_BP: perf_event_x86_regs = 6;
    pub const PERF_REG_X86_SP: perf_event_x86_regs = 7;
    pub const PERF_REG_X86_IP: perf_event_x86_regs = 8;
    pub const PERF_REG_X86_FLAGS: perf_event_x86_regs = 9;
    pub const PERF_REG_X86_CS: perf_event_x86_regs = 10;
    pub const PERF_REG_X86_SS: perf_event_x86_regs = 11;
    pub const PERF_REG_X86_DS: perf_event_x86_regs = 12;
    pub const PERF_REG_X86_ES: perf_event_x86_regs = 13;
    pub const PERF_REG_X86_FS: perf_event_x86_regs = 14;
    pub const PERF_REG_X86_GS: perf_event_x86_regs = 15;
    pub const PERF_REG_X86_R8: perf_event_x86_regs = 16;
    pub const PERF_REG_X86_R9: perf_event_x86_regs = 17;
    pub const PERF_REG_X86_R10: perf_event_x86_regs = 18;
    pub const PERF_REG_X86_R11: perf_event_x86_regs = 19;
    pub const PERF_REG_X86_R12: perf_event_x86_regs = 20;
    pub const PERF_REG_X86_R13: perf_event_x86_regs = 21;
    pub const PERF_REG_X86_R14: perf_event_x86_regs = 22;
    pub const PERF_REG_X86_R15: perf_event_x86_regs = 23;
    pub const PERF_REG_X86_32_MAX: perf_event_x86_regs = 16;
    pub const PERF_REG_X86_64_MAX: perf_event_x86_regs = 24;
    pub const PERF_REG_X86_XMM0: perf_event_x86_regs = 32;
    pub const PERF_REG_X86_XMM1: perf_event_x86_regs = 34;
    pub const PERF_REG_X86_XMM2: perf_event_x86_regs = 36;
    pub const PERF_REG_X86_XMM3: perf_event_x86_regs = 38;
    pub const PERF_REG_X86_XMM4: perf_event_x86_regs = 40;
    pub const PERF_REG_X86_XMM5: perf_event_x86_regs = 42;
    pub const PERF_REG_X86_XMM6: perf_event_x86_regs = 44;
    pub const PERF_REG_X86_XMM7: perf_event_x86_regs = 46;
    pub const PERF_REG_X86_XMM8: perf_event_x86_regs = 48;
    pub const PERF_REG_X86_XMM9: perf_event_x86_regs = 50;
    pub const PERF_REG_X86_XMM10: perf_event_x86_regs = 52;
    pub const PERF_REG_X86_XMM11: perf_event_x86_regs = 54;
    pub const PERF_REG_X86_XMM12: perf_event_x86_regs = 56;
    pub const PERF_REG_X86_XMM13: perf_event_x86_regs = 58;
    pub const PERF_REG_X86_XMM14: perf_event_x86_regs = 60;
    pub const PERF_REG_X86_XMM15: perf_event_x86_regs = 62;
    pub const PERF_REG_X86_XMM_MAX: perf_event_x86_regs = 64;
    pub type perf_event_x86_regs = ::std::os::raw::c_uint;
}
pub use x86::*;
